Genre.create(name: "Fantasy")
Genre.create(name: "Young Adult")
Genre.create(name: "Historical Fiction")
Genre.create(name: "Romance")
Genre.create(name: "Thriller")
Genre.create(name: "Mystery")
Genre.create(name: "Contemporary")
Genre.create(name: "Classic")
